color:
  brandColors:
    - '#000000'
    - '#EDECEC'
    - '#3A3939'
    - '#B7B6B6'
    - '#818080'
  brandStrength: 0.764358
  lightness: 0.5625
  rhythmicContrast: 0.706926
  saturation: 0.744932
layout_spectrum: 0.570946
name: A Little Walk
typography_spectrum: 0.103041
